server:
  servlet:
    context-path:

spring:
  profiles:
    active: @profileActive@
  application:
    name: restful-generator
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/restful-generator
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      username: root
      password: root

springdoc:
  swagger-ui:
    # http://host:port/swagger
    path: /swagger-ui
  api-docs:
    # http://host:port/api-docs
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.transaction: trace
