spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:D:\github\restful-generator\db\restful-generator

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.transaction: trace
    org.hibernate.type.descriptor.sql: trace