server:
  servlet:
    context-path:

spring:
  profiles:
    active: dev
  application:
    name: restful-generator
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:generator.db
    username:
    password:

springdoc:
  swagger-ui:
    # http://localhost:8080/swagger
    path: /swagger
  api-docs:
    # http://localhost:8080/api-docs
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO