name: restful-generator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Start App
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "starter/target/restful-generator-bin.tar.gz"
          remoteDir: "/home/${{ secrets.USERNAME }}/app/"
          options: "--delete --asci"
      - name: Start App
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd /home/${{ secrets.USERNAME }}
            ls -l
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}