name: restful-generator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: deploy app
        uses: garygrossgarten/github-action-scp@release
        with:
          local: starter/target/restful-generator-bin.tar.gz
          remote: /home/${{ secrets.USERNAME }}/app/restful-generator-bin.tar.gz
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: start app
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd /home/${{ secrets.USERNAME }}
            ls
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}