name: restful-generator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy App
        uses: actions/upload-artifact@v3
        with:
          name: application.tar.gz
          path: starter/target/restful-generator-bin.tar.gz
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "starter/target/restful-generator-bin.tar.gz"
          target: "home/${{ secrets.USERNAME }}/app"